### PR TITLE
Draft

### PR DESCRIPTION
**Pull request by jrogol**
After the college draft this week, I created a new data object of historical draft picks. Players were matched by player name (supplemented with some personal knowledge and spot-checking with last names) to obtain `person_id`.

Data includes:

- year
-round
- pick (within round)
- player name
- team name
- college/previous team (related to #4!)
- notes
- id

### CODE REVIEW

**Comment by adror1** [comment]
This is super great, thanks for doing this! I'll be sure to review it in the next couple days.

**Review by adror1 — CHANGES_REQUESTED** [review]
I think the Travis check is failing because the documentation file is missing. Could you also push the `draftpicks.Rd` file? I think that will solve this. If that doesn't work, I think the other solution is to make sure the data is called draft rather than `draftpicks` since the R file is called `draft.R.`

Also, could you convert the column names to snake case for consistency across all dataframes and change nwslTeam to team_id (with the proper team_id from the franchise table)? We're trying to keep these consistent for table joining purposes.

**Comment by jrogol** [comment]
The last couple of commits should resolve this - draftpicks.Rd exists, the "previousTeam" field is now "previous_team," and the "team_id" was pulled from the franchise data.

**Comment by adror1** [comment]
Could you just update the documentation in the `data.R` file to reflect those changes and repush the edited Rd file afterwards? I don't think all the columns are documented properly. Then I can merge the commit.

**Review by adror1 — APPROVED** [review]

**Comment by adror1** [comment]
Hi! A little late for this, but is it alright if I add you as a contributor to the package in the `DESCRIPTION` file? I would really like to make sure you get credit for doing this. If you'd like, you could also do it yourself.

**Comment by jrogol** [comment]
Certainly! I won't get around to it for a few days, as I'm on vacation, though!

**Pull request merged**
