### PR TITLE
Create get_locations.R

### PR DESCRIPTION
**Pull request by robert-frey**
A function that will parse out data to obtain shot player name, player name of the assist, shot on goal location, shot type (ie left foot, right foot, header), shot location if not shot on goal, as well as adding plots of either shot on goal location from the pitch perspective or from the goal perspective.

### CODE REVIEW

**Comment by adror1** [comment]
Yay! So excited for this, I'll do some work to bring it into the package. Could you also push the `.csv` you mentioned so that I can do some cross referencing?

**Comment by adror1** [comment]
Hi @robert-frey, 
I'm trying to pull your files, but it's not letting me. Could you check that you've checked "Allow edits from maintainers?" in your pull request?

**Comment by robert-frey** [comment]
It's checked!

**Comment by adror1** [comment]
Hi @robert-frey, 
I did some editing to your function to make it a bit more general, so that we can build upon it later like I mentioned to you yesterday. It's now named `get_events`. I removed the visualization function for now, but I'll integrate that at another time, since it will need to work with a generalized version of this function. Also, I saw in the comment that you were struggling with the regexes for the right side, is that still the case? I didn't look into that too much. Whenever you get a chance, can you let me know if the changes are alright with you?

**Comment by robert-frey** [comment]
Yes, that is still the case, unfortunately. Maybe pass str_detect specifically for the right side? The changes look great! I can't wait!

**Pull request merged**
